config/routes.rb
Cfp::Application.routes.draw do
  get "home/show"
  get "guide", :to => "pages#guide"
  get "mentorship", :to => "pages#mentorship"

  get '/auth/:provider/callback' => 'authentications#create'

  devise_for :users, :controllers => {
    :registrations => 'registrations',
    :sessions => 'sessions',
    :passwords => 'passwords'
  }

  resource   :profile
  resources  :calls do
    resources :proposed_speakers, only: [:new, :create]
  end
  resources  :talks
  resources  :proposed_speakers, only: [:destroy, :index]
  resources  :authentications

  namespace :admin do
    resources :proposed_speakers, only: [:index] do
      collection do
        get :export
      end
    end
    resources :proposals, only: [:update, :show] do
      collection do
        get :export
      end
      member do
        post :note, :to => "notes#create"
        patch :note, :to => "notes#update"

        resource :user_proposal_rating, only: [:create, :update]
      end
    end
    resources :calls, only: :index do
      resources :proposals
    end
    resources :users do
      collection do
        get :export
      end
    end
    resources :communications do
      member do
        post :deliver
      end
    end
    root :to => "calls#index", as: :root
  end

  namespace :mentor do
    resources :talks, only: [:index]

    post "feedbacks/:id", :to => "feedbacks#contact", as: :feedback

    root :to => "talks#index", as: :root
  end
  root :to => "home#show"
end

app/views/main/_counters.html.erb
<div class="counters">
  <span>
    <h1 class="muted"><%= @proposal_counts.size %></h1>
    <small>open calls have received proposals</small>
  </span>
  <% @proposal_counts.each do |call, count| %>
  <span>
    <h1 class="muted"><%= count %></h1>
    <small>proposals<br/><%= call.title %></small>
  </span>
  <% end %>
  <span>
    <h1 class="muted"><%= @user_count %></h1>
    <small>users registered</small>
  </span>
</div>

app/views/main/_footer.html.erb
<footer class="row">
  <div class="small-12 columns">
    <p><%= t('footer.explanatory_html') %></p>
    <%# render 'main/counters' %>
  </div>
</footer>
<div class="hosted_by show-for-large-up"></div>

app/views/main/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/main/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to 'Call for Proposals', root_path %></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul class="left">
      <%= render 'main/navigation_links' %>
    </ul>

    <% if current_user %>
      <ul class="right">
        <li><%= link_to t('nav.main.logout'), destroy_user_session_path, method: :delete %></li>
      </ul>
    <% end %>
  </div>
</nav>

app/views/main/_navigation_links.html.erb
<% if current_user %>
  <li><%= link_to t('nav.main.papers'), talks_path %></li>
  <li><%= link_to t('nav.main.profile'), profile_path %></li>
  <% if current_user.mentor? %>
    <li><%= link_to t('nav.main.mentor'), mentor_root_path %></li>
  <% end %>
  <% if current_user.staff? %>
    <li><%= link_to t('nav.main.admin'), admin_root_path %></li>
  <% end %>
<% end %>
<li><%= link_to t('nav.main.guide'), guide_path %></li>
<li><%= link_to t('nav.main.mentorship'), mentorship_path %></li>
<li><%= link_to t('nav.main.coc'), Settings.conference.coc_link, target: '_blank' %></li>