config/routes.rb
Cfp::Application.routes.draw do
  get "home/show"
  get "guide", :to => "pages#guide"
  get "mentorship", :to => "pages#mentorship"

  get '/auth/:provider/callback' => 'authentications#create'

  devise_for :users, :controllers => {
    :registrations => 'registrations',
    :sessions => 'sessions',
    :passwords => 'passwords'
  }

  resource   :profile
  resources  :calls do
    resources :proposed_speakers, only: [:new, :create]
  end
  resources  :talks
  resources  :proposed_speakers, only: [:destroy, :index]
  resources  :authentications

  namespace :admin do
    resources :proposed_speakers, only: [:index] do
      collection do
        get :export
      end
    end
    resources :proposals, only: [:update, :show] do
      collection do
        get :export
      end
      member do
        post :note, :to => "notes#create"
        patch :note, :to => "notes#update"

        resource :user_proposal_rating, only: [:create, :update]
      end
    end
    resources :calls, only: :index do
      resources :proposals
    end
    resources :users do
      collection do
        get :export
      end
    end
    resources :communications do
      member do
        post :deliver
      end
    end
    root :to => "calls#index", as: :root
  end

  namespace :mentor do
    resources :talks, only: [:index]

    post "feedbacks/:id", :to => "feedbacks#contact", as: :feedback

    root :to => "talks#index", as: :root
  end
  root :to => "home#show"
end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
  has_many :notes
  belongs_to :talk

  self.primary_key = 'id'

  before_validation on: :create do
    self.id = SecureRandom.hex(16)
  end

  delegate :user, to: :talk

  belongs_to :call
  has_many :user_proposal_ratings, inverse_of: :proposal, dependent: :destroy
  has_many :ratings, through: :user_proposal_ratings

  validates :call, :talk, presence: true

  scope :visible, -> { joins(:call).merge(Call.not_archived) }
  scope :for_open_call, -> { joins(:call).merge(Call.open) }
  scope :editable, -> { for_open_call.readonly(false) }
  scope :mentors_can_read, -> { joins(:talk).where('talks.mentors_can_read': true) }
  scope :not_from, -> user { joins(:talk).where.not('talks.user_id': user.id) }
  scope :selected, -> { where(selected: true) }

  delegate :title, :open?, to: :call, prefix: :call
  delegate :title, :public_description, :private_description, :time_slot, :mentor_name, :mentors_can_read, to: :talk, prefix: :talk

  def rated_by?(user)
    user_proposal_ratings.where(user_id: user.id).one?
  end

  def note_attached_by?(user)
    notes.where(user_id: user.id).one?
  end

  def score
    sum_of_votes = ratings.sum(:vote)
    sum_of_votes / user_proposal_ratings.size.to_f
  end

  def score_by_dimension(dimension)
    sum_of_votes = ratings.in_dimension(dimension).sum(:vote)
    sum_of_votes / user_proposal_ratings.size.to_f
  end

  class << self
    def not_rated_by_user(user)
      where.not(id: user.user_proposal_ratings.select(:proposal_id))
    end
  end

  def user_email
    talk.user.email
  end

  def user_name
    talk.user.name
  end
end

app/controllers/admin/proposals_controller.rb
class Admin::ProposalsController < Admin::AdminController
  def index
    @call = Call.find(params[:call_id])
    @dimensions = RatingDimension.all
    @proposals = @call.proposals.visible.joins(:talk).order('selected DESC, track ASC, time_slot ASC, created_at DESC').to_a
    if params[:sort]
      @proposals.sort_by! do |p|
        score = p.score
        if score.nan?
          -1
        else
          score
        end
      end
      @proposals.reverse!
    end
    @proposals = Admin::ProposalDecorator.wrap(@proposals)
  end

  def update
    proposal_parameters = params[:proposal]
    proposal_parameters.permit(:selected)
    @proposal = Proposal.find(params[:id])
    @proposal.selected = proposal_parameters[:selected]
    @proposal.save!
    redirect_to talk_path(@proposal.talk)
  end

  def show
    @proposal = Proposal.find(params[:id])
    @user_proposal_rating = current_user.user_proposal_rating_for_proposal(@proposal)
  end

  def export
    @proposals = Proposal.joins(:talk).order('selected DESC, track ASC, talks.time_slot ASC, created_at DESC')

    respond_to do |format|
      format.csv do
        csv_response = build_csv(@proposals, export_columns)
        send_data(csv_response, filename: 'proposals.csv', disposition: 'attachment', type: 'text/csv; charset=utf-8; header=present')
      end
    end
  end

  private

  def export_columns
    # Handle call_id, user_id (when deanonymized)
    %w(
      id
      user_name
      user_email
      talk_title
      talk_public_description
      talk_private_description
      selected
      score
      talk_time_slot
      track
      created_at
      updated_at
    )
  end

end

app/views/admin/proposals/index.html.erb
<h1>
  <%= t('.title') %>
  <small><%= t('.subtitle', count: current_user.user_proposal_ratings.count) %></small>
</h1>

<dl class="sub-nav">
  <dt>Sort:</dt>
  <% if params[:sort] %>
    <dd><%= link_to('Unsorted', {}) %></dd>
    <dd class="active"><a href="#">By score</a></dd>
  <% else %>
    <dd class="active"><a href="#">Unsorted</a></dd>
    <dd><%= link_to('By score', { :sort => true }) %></dd>
  <% end %>
</dl>

<div class="papers">
  <% if @proposals.empty? %>
    No submissions yet.
  <% else %>
    <table class="table table-header-rotated">
      <thead>
        <tr>
          <th><%= t('activerecord.models.attributes.paper.position') %></th>
          <th><%= t('activerecord.models.attributes.paper.call') %></th>
          <th><%= t('activerecord.models.attributes.paper.time_slot') %></th>
          <th><%= t('activerecord.models.attributes.paper.id') %></th>
          <th><%= t('activerecord.models.attributes.paper.title') %></th>
          <th class="rotate"><span><%= t('activerecord.models.attributes.paper.created_at') %></span></th>
          <th class="rotate"><span><%= t('activerecord.models.attributes.paper.updated_at') %></span></th>
          <th class="rotate"><span><%= t('activerecord.models.attributes.paper.user') %></span></th>
          <th class="rotate"><span><%= t('activerecord.models.attributes.paper.rated_by_you') %></span></th>
          <th class="rotate"><span><%= t('activerecord.models.attributes.paper.notice_by_you') %></span></th>
          <th class="rotate"><span><%= t('activerecord.models.attributes.paper.number_of_ratings') %></span></th>
          <th class="rotate"><span><%= t('activerecord.models.attributes.paper.score') %></span></th>
          <% @dimensions.each do |d| %>
            <th class="rotate"><span><%= d.name %></span></th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @proposals.each_with_index do |proposal,index| %>
          <tr class="<%= 'selected' if proposal.selected? %>">
            <td class="rank"><%= index + 1 %></td>
            <td><%= proposal.call_title %></td>
            <td class="time-slot"><%= proposal.formatted_time_slot %></td>
            <td class="id"><%= proposal.id[0..5] %></td>
            <th class="title"><%= link_to truncate(proposal.talk_title, length: 60), admin_proposal_path(proposal) %></th>
            <td><%= proposal.formatted_created_at %></td>
            <td><%= proposal.formatted_updated_at %></td>
            <td><%= link_to(proposal.user.name, profile_path(proposal.user)) if proposal.call.deanonymized? %></td>
            <td><%= "✔" if proposal.rated_by?(current_user) %></td>
            <td><%= "✔" if proposal.note_attached_by?(current_user) %></td>
            <td score="ratings"><%= proposal.user_proposal_ratings.count %></td>
            <td class="score"><%= proposal.formatted_score %></td>
            <% @dimensions.each do |d| %>
              <td class="score"><%= proposal.formatted_score_by_dimension(d) %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

<%= link_to 'Export (CSV)', export_admin_proposals_path(format: 'csv'), class: 'button' %>
<%= render "admin/main/nav_bar" %>

app/views/admin/proposals/show.html.erb
<%= render 'talks/talk_details', talk: @proposal.talk %>


<h3><%= t('admin.admin_section') %></h3>
<% if @proposal.call.open? %>
  <%= t('admin.call_is_still_open') %>
<% else %>
  <% if @proposal.call.anonymous? then %>
    <h4><%= t('admin.votes') %></h4>
    <%= simple_form_for @user_proposal_rating, url: admin_user_proposal_rating_path(@proposal) do |f| %>
      <% RatingDimension.all.each do |rating_dimension| %>
        <h6><%= rating_dimension.name %></h6>
        <%= f.fields_for :ratings, f.object.rating_for_rating_dimension(rating_dimension) do |rating_form| %>
          <%= rating_form.hidden_field :id %>
          <%= rating_form.hidden_field :rating_dimension_id %>
          <%= rating_form.input :vote, as: :votes %>
        <% end %>
      <% end %>
      <%= f.submit 'Vote', class: 'button' %>
      <%= f.submit 'Vote and go to proposal list', class: 'button' %>
      <%= f.submit 'Vote and go to next proposal', class: 'button' %>
    <% end %>
  <% else %>
    <%= render 'talks/talk_user_details', talk: @proposal.talk %>
  <% end %>

  <h4><%= t('admin.attach_personal_note') %></h4>
  <%= simple_form_for current_user.note_for_proposal(@proposal), :url => note_admin_proposal_path(@proposal) do |f| %>
    <%= f.input :content, required: true, input_html: {rows: 10} %>
    <%= f.submit class: 'button' %>
  <% end %>

  <h4><%= t('admin.select_paper') %></h4>
  <%= simple_form_for @proposal, :url => admin_proposal_path(@proposal) do |f| %>
    <%= f.input :selected %>
    <%= f.submit class: 'button' %>
  <% end %>
<% end %>