config/routes.rb
Cfp::Application.routes.draw do
  get "home/show"
  get "guide", :to => "pages#guide"
  get "mentorship", :to => "pages#mentorship"

  get '/auth/:provider/callback' => 'authentications#create'

  devise_for :users, :controllers => {
    :registrations => 'registrations',
    :sessions => 'sessions',
    :passwords => 'passwords'
  }

  resource   :profile
  resources  :calls do
    resources :proposed_speakers, only: [:new, :create]
  end
  resources  :talks
  resources  :proposed_speakers, only: [:destroy, :index]
  resources  :authentications

  namespace :admin do
    resources :proposed_speakers, only: [:index] do
      collection do
        get :export
      end
    end
    resources :proposals, only: [:update, :show] do
      collection do
        get :export
      end
      member do
        post :note, :to => "notes#create"
        patch :note, :to => "notes#update"

        resource :user_proposal_rating, only: [:create, :update]
      end
    end
    resources :calls, only: :index do
      resources :proposals
    end
    resources :users do
      collection do
        get :export
      end
    end
    resources :communications do
      member do
        post :deliver
      end
    end
    root :to => "calls#index", as: :root
  end

  namespace :mentor do
    resources :talks, only: [:index]

    post "feedbacks/:id", :to => "feedbacks#contact", as: :feedback

    root :to => "talks#index", as: :root
  end
  root :to => "home#show"
end

app/models/talk.rb
class Talk < ActiveRecord::Base
  has_many :proposals, dependent: :destroy
  has_many :calls, through: :proposals

  self.primary_key = 'id'

  before_validation on: :create do
    self.id = SecureRandom.hex(16)
  end

  belongs_to :user

  validates :id, :title, :public_description, :private_description, :time_slot, presence: true
  validates :user, presence: true
  validates_acceptance_of :terms_and_conditions, if: -> { new_record? }
  validates :calls, length: { minimum: 1 }
  attr_accessor :terms_and_conditions

  scope :not_from, -> user { where.not('user_id': user.id) }
  scope :for_open_call, -> { joins(:calls).merge(Call.open) }
  scope :mentors_can_read, -> { where('mentors_can_read': true) }

  accepts_nested_attributes_for :user, update_only: true

  def updated?
    created_at != updated_at
  end

  def editable?
    proposals.all?(&:call_open?)
  end
end

app/controllers/admin/talks_controller.rb
class Admin::TalksController < Admin::AdminController
  def index
    @dimensions = RatingDimension.all
    @proposals = Proposal.visible.joins(:talk).order('selected DESC, track ASC, time_slot ASC, created_at DESC').to_a
    if params[:sort]
      @proposals.sort_by! do |p|
        score = p.score
        if score.nan?
          -1
        else
          score
        end
      end
      @proposals.reverse!
    end
    @proposals = Admin::ProposalDecorator.wrap(@proposals)
  end

  def update
    proposal_parameters = params[:proposal]
    proposal_parameters.permit(:selected)
    @proposal = Proposal.find(params[:id])
    @proposal.selected = proposal_parameters[:selected]
    @proposal.save!
    redirect_to talk_path(@proposal.talk)
  end

  def export
    @proposals = Proposal.joins(:talk).order('selected DESC, track ASC, talks.time_slot ASC, created_at DESC')

    respond_to do |format|
      format.csv do
        csv_response = build_csv(@proposals, export_columns)
        send_data(csv_response, filename: 'proposals.csv', disposition: 'attachment', type: 'text/csv; charset=utf-8; header=present')
      end
    end
  end

  private

  def export_columns
    # Handle call_id, user_id (when deanonymized)
    %w(
      id
      user_name
      user_email
      talk_title
      talk_public_description
      talk_private_description
      selected
      score
      talk_time_slot
      track
      created_at
      updated_at
    )
  end

end

app/controllers/mentor/talks_controller.rb
class Mentor::TalksController < Mentor::MentorController
  def index
    @talks = Talk.for_open_call.not_from(current_user).mentors_can_read.order('created_at DESC')
  end
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  skip_before_filter :authenticate, only: :show

  def index
    @talks = current_user.talks.order("created_at DESC")
    @open_calls = Call.open
  end

  def show
    @talk = Talk.find(params[:id])
  end

  def new
    @talk = current_user.talks.new
    @open_calls = Call.open
  end

  def edit
    @talk = current_user.talks.find(params[:id])
    @open_calls = Call.open
  end

  def create
    @talk = current_user.talks.new(talk_params.except(:user_attributes))
    @talk.track = 'Test'
    if @talk.save && update_user_params
      notify_excited_organizers
      redirect_to @talk, notice: I18n.t('papers.create.success')
    else
      render_new_with_open_calls
    end
  end

  def update
    @talk = current_user.talks.find(params[:id])

    if @talk.update_attributes(talk_params)
      redirect_to @talk, notice: I18n.t('papers.update.success')
    else
      render :edit
    end
  end

  def destroy
    talk = current_user.talks.find(params[:id])
    talk.destroy

    redirect_to talks_url
  end

  private

  def update_user_params
    if talk_params[:user_attributes]
      @talk.user_attributes = talk_params[:user_attributes]
    end
    @talk.save
  end

  def render_new_with_open_calls
    @open_calls = Call.open
    render :new
  end

  def notify_excited_organizers
    ProposalsMailer.created(@talk.title, talk_url(@talk)).deliver_now
  end

  def talk_params
    params.require(:talk).permit(
      :title, :public_description, :private_description, :time_slot,
      :mentor_name, :mentors_can_read, :terms_and_conditions,
      user_attributes: [:gender, :mentor, :bio],
      call_ids: []
    )
  end
end

app/views/talks/_form.html.erb
<%= simple_form_for @talk do |f| %>
  <%= f.error_notification %>

  <div class="inputs row">
    <div class="small-8 columns">
      <h2><%= t('.proposal') %></h2>
      <%= f.input :title %>
      <%= f.input :public_description, required: true, as: :text, input_html: {rows: 5} %>
      <%= f.input :private_description, required: true, as: :text, input_html: {rows: 5} %>

      <%= f.input :time_slot, :collection => Settings.conference.time_slots %>

      <%= f.input :mentor_name %>
      <%= f.input :mentors_can_read %>
    </div>
    <div class="small-4 columns">
      <h2><%= t('profile') %></h2>
      <%= f.fields_for :user do |uf| %>
        <%= uf.input :gender, collection: [:male, :female, :unspecified], include_blank: '(leave empty)' %>
        <%= uf.input :bio %>
        <%= uf.input :mentor %>
      <% end %>
    </div>
  </div>
  <hr>
  <div>
    <% if @talk.calls.all?(&:open?) %>
      <%= f.association :calls, collection: @open_calls, as: :check_boxes, label: t('.i-want-to-submit-this-to-the-following-conferences') %>
    <% end %>
  </div>
  <hr>

  <div class="actions">
    <% if @talk.new_record? then %>
      <% label = raw t('simple_form.hints.paper.code_of_conduct_acceptance') % { :code_of_conduct_link => link_to(t('simple_from.hints.paper.code_of_conduct_text'), Settings.conference.coc_link, :target => '_blank') } %>
      <%= f.input :terms_and_conditions, as: :boolean, required: true, label: label %>
    <% end %>
    <%= f.button :submit, class: 'button' %>
  </div>
<% end %>

app/views/talks/_proposal_admin_section.html.erb
<% unless @proposal.call.anonymous? %>
  <h4><%= t('activerecord.models.attributes.bio') %></h4>
  <p><strong><%= t('activerecord.models.attributes.user.name') %>:</strong>
  <%= @proposal.user.name %></p>
  <p><strong><%= t('activerecord.models.attributes.user.email') %>:</strong>
  <%= @proposal.user.email %></p>
  <p><strong><%= t('activerecord.models.attributes.user.github_handle') %>:</strong>
  <%= @proposal.user.github_handle %></p>
  <p><strong><%= t('activerecord.models.attributes.user.twitter_handle') %>:</strong>
  <%= @proposal.user.twitter_handle %></p>
  <p><strong><%= t('activerecord.models.attributes.user.bio') %>:</strong>
  <%= @proposal.user.bio %></p>
<% end %>

<h3><%= t('admin.admin_section') %></h3>
<% unless @proposal.call.open? %>
  <% if @proposal.call.anonymous? then %>
    <h4><%= t('admin.votes') %></h4>
    <%= simple_form_for @user_proposal_rating, url: admin_user_proposal_rating_path(@proposal) do |f| %>
      <% RatingDimension.all.each do |rating_dimension| %>
        <h6><%= rating_dimension.name %></h6>
        <%= f.fields_for :ratings, f.object.rating_for_rating_dimension(rating_dimension) do |rating_form| %>
          <%= rating_form.hidden_field :id %>
          <%= rating_form.hidden_field :rating_dimension_id %>
          <%= rating_form.input :vote, as: :votes %>
        <% end %>
      <% end %>
      <%= f.submit 'Vote', class: 'button' %>
      <%= f.submit 'Vote and go to papers list', class: 'button' %>
      <%= f.submit 'Vote and go to next paper', class: 'button' %>
    <% end %>
  <% end %>

  <h4><%= t('admin.attach_personal_note') %></h4>
  <%= simple_form_for current_user.note_for_proposal(@proposal), :url => note_admin_proposal_path(@proposal) do |f| %>
    <%= f.input :content, required: true, input_html: {rows: 10} %>
    <%= f.submit class: 'button' %>
  <% end %>

  <h4><%= t('admin.select_paper') %></h4>
  <%= simple_form_for @proposal, :url => admin_proposal_path(@proposal) do |f| %>
    <%= f.input :selected %>
    <%= f.submit class: 'button' %>
  <% end %>
<% end %>

app/views/talks/_talk_details.html.erb
<h1><%= talk.title %></h1>

<div class="papers">
  <div class="time-slot"><%= talk.time_slot %></div>

  <div class="descriptions">
    <h4><%= t('activerecord.models.attributes.paper.private_description') %></h4>
    <%= markdown talk.private_description %>

    <% if talk.public_description.present? %>
      <hr>
      <h4><%= t('activerecord.models.attributes.paper.public_description') %></h4>
      <%= markdown talk.public_description %>
    <% end %>
  </div>
</div>

app/views/talks/_talk_user_details.html.erb
<h4><%= t('activerecord.models.attributes.bio') %></h4>
<p><strong><%= t('activerecord.models.attributes.user.name') %>:</strong>
  <%= talk.user.name %></p>
<p><strong><%= t('activerecord.models.attributes.user.email') %>:</strong>
  <%= talk.user.email %></p>
<p><strong><%= t('activerecord.models.attributes.user.github_handle') %>:</strong>
  <%= talk.user.github_handle %></p>
<p><strong><%= t('activerecord.models.attributes.user.twitter_handle') %>:</strong>
  <%= talk.user.twitter_handle %></p>
<p><strong><%= t('activerecord.models.attributes.user.bio') %>:</strong>
  <%= talk.user.bio %></p>

app/views/talks/edit.html.erb
<h1><%= t('.title') %></h1>

<div class="papers">
  <%= render 'form' %>
</div>

app/views/talks/index.html.erb
<h1><%= t('.title') %></h1>

<div class="papers">
  <% if @talks.empty? %>
    No submissions yet? Create one now and give us a solid reason to choose you!
  <% else %>
    <table class="table">
      <tr>
        <th>Call</th>
        <th>Title</th>
        <th>Created at</th>
        <th></th>
      </tr>

      <% @talks.each do |talk| %>
        <tr>
          <%# <td class="call"><%= talk.call_title %1></td> %>
          <td class="title"><%= talk.title %></td>
          <td><%= talk.created_at.strftime('%B %d, %Y') %></td>
          <td>
            <%= link_to 'show', talk_path(talk.id) %>
            <% if talk.editable? %>
              <%= link_to 'edit', edit_talk_path(talk) %>
              <%= link_to 'destroy', talk, data: { confirm: 'Are you sure?' }, method: :delete %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  <% end %>
</div>

<% if @open_calls.empty? %>
  <p>There are currently no open calls for proposals.</p>
<% else %>
  <p><%= link_to 'New talk', new_talk_path, class: 'button' %></p>
<% end %>

app/views/talks/new.html.erb
<h1><%= t('.title') %></h1>

<div class="papers">
  <%= render 'form' %>
</div>

app/views/talks/show.html.erb
<%= render 'talk_details', talk: @talk %>

<hr>
<h4><%= t('.proposed-for-these-conferences') %></h4>

<ul>
<% @talk.calls.each do |call| %>
  <li><%= call.title %></li>
<% end %>
</ul>

<% if current_user %>
  <% if current_user.can_edit_talk?(@talk) && @talk.editable? %>
    <%= link_to 'Edit', edit_talk_path(@talk), class: 'button' %>
  <% elsif @talk.editable? %>
    <h3><%= t('feedback.title') %></h3>
    <%= simple_form_for Feedback.new, url: mentor_feedback_path(@talk) do |f| %>
      <%= f.input :feedback, as: :text, required: true, input_html: {rows: 10} %>
      <%= f.submit t('feedback.submit'), class: 'button' %>
    <% end %>
    <p>
      <%= t('feedback.explanation') %>
    </p>
  <% end %>
  <% if current_user.staff? && @talk.calls.none?(&:anonymous?) %>
    <%= render "talks/talk_user_details", talk: @talk %>
  <% end %>
<% end %>