config/routes.rb
Cfp::Application.routes.draw do
  get "home/show"
  get "guide", :to => "pages#guide"
  get "mentorship", :to => "pages#mentorship"

  get '/auth/:provider/callback' => 'authentications#create'

  devise_for :users, :controllers => {
    :registrations => 'registrations',
    :sessions => 'sessions',
    :passwords => 'passwords'
  }

  resource   :profile
  resources  :calls do
    resources :proposed_speakers, only: [:new, :create]
  end
  resources  :talks
  resources  :proposed_speakers, only: [:destroy, :index]
  resources  :authentications

  namespace :admin do
    resources :proposed_speakers, only: [:index] do
      collection do
        get :export
      end
    end
    resources :proposals, only: [:update, :show] do
      collection do
        get :export
      end
      member do
        post :note, :to => "notes#create"
        patch :note, :to => "notes#update"

        resource :user_proposal_rating, only: [:create, :update]
      end
    end
    resources :calls, only: :index do
      resources :proposals
    end
    resources :users do
      collection do
        get :export
      end
    end
    resources :communications do
      member do
        post :deliver
      end
    end
    root :to => "calls#index", as: :root
  end

  namespace :mentor do
    resources :talks, only: [:index]

    post "feedbacks/:id", :to => "feedbacks#contact", as: :feedback

    root :to => "talks#index", as: :root
  end
  root :to => "home#show"
end

app/models/talk.rb
class Talk < ActiveRecord::Base
  has_many :proposals, dependent: :destroy
  has_many :calls, through: :proposals

  self.primary_key = 'id'

  before_validation on: :create do
    self.id = SecureRandom.hex(16)
  end

  belongs_to :user

  validates :id, :title, :public_description, :private_description, :time_slot, presence: true
  validates :user, presence: true
  validates_acceptance_of :terms_and_conditions, if: -> { new_record? }
  validates :calls, length: { minimum: 1 }
  attr_accessor :terms_and_conditions

  scope :not_from, -> user { where.not('user_id': user.id) }
  scope :for_open_call, -> { joins(:calls).merge(Call.open) }
  scope :mentors_can_read, -> { where('mentors_can_read': true) }

  accepts_nested_attributes_for :user, update_only: true

  def updated?
    created_at != updated_at
  end

  def editable?
    proposals.all?(&:call_open?)
  end
end

app/controllers/admin/talks_controller.rb
class Admin::TalksController < Admin::AdminController
  def index
    @dimensions = RatingDimension.all
    @proposals = Proposal.visible.joins(:talk).order('selected DESC, track ASC, time_slot ASC, created_at DESC').to_a
    if params[:sort]
      @proposals.sort_by! do |p|
        score = p.score
        if score.nan?
          -1
        else
          score
        end
      end
      @proposals.reverse!
    end
    @proposals = Admin::ProposalDecorator.wrap(@proposals)
  end

  def update
    proposal_parameters = params[:proposal]
    proposal_parameters.permit(:selected)
    @proposal = Proposal.find(params[:id])
    @proposal.selected = proposal_parameters[:selected]
    @proposal.save!
    redirect_to talk_path(@proposal.talk)
  end

  def export
    @proposals = Proposal.joins(:talk).order('selected DESC, track ASC, talks.time_slot ASC, created_at DESC')

    respond_to do |format|
      format.csv do
        csv_response = build_csv(@proposals, export_columns)
        send_data(csv_response, filename: 'proposals.csv', disposition: 'attachment', type: 'text/csv; charset=utf-8; header=present')
      end
    end
  end

  private

  def export_columns
    # Handle call_id, user_id (when deanonymized)
    %w(
      id
      user_name
      user_email
      talk_title
      talk_public_description
      talk_private_description
      selected
      score
      talk_time_slot
      track
      created_at
      updated_at
    )
  end

end

app/controllers/mentor/talks_controller.rb
class Mentor::TalksController < Mentor::MentorController
  def index
    @talks = Talk.for_open_call.not_from(current_user).mentors_can_read.order('created_at DESC')
  end
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  skip_before_filter :authenticate, only: :show

  def index
    @talks = current_user.talks.order("created_at DESC")
    @open_calls = Call.open
  end

  def show
    @talk = Talk.find(params[:id])
  end

  def new
    @talk = current_user.talks.new
    @open_calls = Call.open
  end

  def edit
    @talk = current_user.talks.find(params[:id])
    @open_calls = Call.open
  end

  def create
    @talk = current_user.talks.new(talk_params.except(:user_attributes))
    @talk.track = 'Test'
    if @talk.save && update_user_params
      notify_excited_organizers
      redirect_to @talk, notice: I18n.t('papers.create.success')
    else
      render_new_with_open_calls
    end
  end

  def update
    @talk = current_user.talks.find(params[:id])

    if @talk.update_attributes(talk_params)
      redirect_to @talk, notice: I18n.t('papers.update.success')
    else
      render :edit
    end
  end

  def destroy
    talk = current_user.talks.find(params[:id])
    talk.destroy

    redirect_to talks_url
  end

  private

  def update_user_params
    if talk_params[:user_attributes]
      @talk.user_attributes = talk_params[:user_attributes]
    end
    @talk.save
  end

  def render_new_with_open_calls
    @open_calls = Call.open
    render :new
  end

  def notify_excited_organizers
    ProposalsMailer.created(@talk.title, talk_url(@talk)).deliver_now
  end

  def talk_params
    params.require(:talk).permit(
      :title, :public_description, :private_description, :time_slot,
      :mentor_name, :mentors_can_read, :terms_and_conditions,
      user_attributes: [:gender, :mentor, :bio],
      call_ids: []
    )
  end
end

app/views/admin/talks/index.html.erb
<h1>
  <%= t('.title') %>
  <small><%= t('.subtitle', count: current_user.user_proposal_ratings.count) %></small>
</h1>

<dl class="sub-nav">
  <dt>Sort:</dt>
  <% if params[:sort] %>
    <dd><%= link_to('Unsorted', {}) %></dd>
    <dd class="active"><a href="#">By score</a></dd>
  <% else %>
    <dd class="active"><a href="#">Unsorted</a></dd>
    <dd><%= link_to('By score', { :sort => true }) %></dd>
  <% end %>
</dl>

<div class="papers">
  <% if @proposals.empty? %>
    No submissions yet.
  <% else %>
    <table class="table table-header-rotated">
      <thead>
        <tr>
          <th><%= t('activerecord.models.attributes.paper.position') %></th>
          <th><%= t('activerecord.models.attributes.paper.call') %></th>
          <th><%= t('activerecord.models.attributes.paper.time_slot') %></th>
          <th><%= t('activerecord.models.attributes.paper.id') %></th>
          <th><%= t('activerecord.models.attributes.paper.title') %></th>
          <th class="rotate"><span><%= t('activerecord.models.attributes.paper.created_at') %></span></th>
          <th class="rotate"><span><%= t('activerecord.models.attributes.paper.updated_at') %></span></th>
          <th class="rotate"><span><%= t('activerecord.models.attributes.paper.user') %></span></th>
          <th class="rotate"><span><%= t('activerecord.models.attributes.paper.rated_by_you') %></span></th>
          <th class="rotate"><span><%= t('activerecord.models.attributes.paper.notice_by_you') %></span></th>
          <th class="rotate"><span><%= t('activerecord.models.attributes.paper.number_of_ratings') %></span></th>
          <th class="rotate"><span><%= t('activerecord.models.attributes.paper.score') %></span></th>
          <% @dimensions.each do |d| %>
            <th class="rotate"><span><%= d.name %></span></th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @proposals.each_with_index do |proposal,index| %>
          <tr class="<%= 'selected' if proposal.selected? %>">
            <td class="rank"><%= index + 1 %></td>
            <td><%= proposal.call_title %></td>
            <td class="time-slot"><%= proposal.formatted_time_slot %></td>
            <td class="id"><%= proposal.id[0..5] %></td>
            <th class="title"><%= link_to truncate(proposal.talk_title, length: 60), proposal.talk %></th>
            <td><%= proposal.formatted_created_at %></td>
            <td><%= proposal.formatted_updated_at %></td>
            <td><%= link_to(proposal.user.name, profile_path(proposal.user)) if proposal.call.deanonymized? %></td>
            <td><%= "✔" if proposal.rated_by?(current_user) %></td>
            <td><%= "✔" if proposal.note_attached_by?(current_user) %></td>
            <td score="ratings"><%= proposal.user_proposal_ratings.count %></td>
            <td class="score"><%= proposal.formatted_score %></td>
            <% @dimensions.each do |d| %>
              <td class="score"><%= proposal.formatted_score_by_dimension(d) %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

<%= link_to 'Export (CSV)', export_admin_talks_path(format: 'csv'), class: 'button' %>
<%= render "admin/main/nav_bar" %>